# Generated by Django 4.1.7 on 2023-04-01 01:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150)])),
                ('sobrenome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.MaxLengthValidator(14)])),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=120)),
                ('numero_rua', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=15)),
                ('sinopse', models.CharField(max_length=300)),
                ('sensura', models.CharField(max_length=25)),
                ('avaliacoes', models.ManyToManyField(blank=True, to='app.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_locacao', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Data e hora da locação')),
                ('locou', models.ManyToManyField(blank=True, to='app.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolucao_avaliacao', models.ManyToManyField(blank=True, to='app.avaliacao')),
                ('filme_devolucao', models.ManyToManyField(blank=True, to='app.filme')),
            ],
        ),
        migrations.AddField(
            model_name='cadastro',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco'),
        ),
    ]
